name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
      - run: yarn install
      - run: yarn pub
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
